#!/usr/bin/env bash
# Build the rzk logic core to WebAssembly for the playground.
#
# Requires the GHC WebAssembly toolchain (ghc-wasm-meta); source its env first,
# e.g. `source ~/.ghc-wasm/env`. Produces two artefacts under rzk-playground/public:
#
#   rzk-js.wasm                    the reactor module (exports `rzkTypecheck`)
#   rzk-js.ghc_wasm_jsffi.js       the JSFFI glue generated by GHC's post-linker
#
# The playground loads them with @bjorn3/browser_wasi_shim (see src/rzk.ts).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
out="$root/rzk-playground/public"

cd "$root"

# LSP off: the `lsp` package is not needed for the frontend and is kept off the
# wasm build, exactly as the wasm.yml CI lane and the old GHCJS build did.
wasm32-wasi-cabal build rzk-js --flags=-lsp

wasm="$(wasm32-wasi-cabal list-bin rzk-js --flags=-lsp)"
libdir="$(wasm32-wasi-ghc --print-libdir)"

mkdir -p "$out"
cp "$wasm" "$out/rzk-js.wasm"
"$libdir/post-link.mjs" -i "$wasm" -o "$out/rzk-js.ghc_wasm_jsffi.js"

echo "wrote $out/rzk-js.wasm ($(du -h "$out/rzk-js.wasm" | cut -f1))"
echo "wrote $out/rzk-js.ghc_wasm_jsffi.js"
