{-# LANGUAGE CPP               #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
{-# LANGUAGE TemplateHaskell   #-}

-- | Which build of rzk this is: the package version, the commit it was built
-- from (when the build supplied one), the compiler and platform, and whether
-- LSP support was compiled in.
--
-- The package version itself is generated by Cabal into @Paths_rzk@, an
-- autogenerated /other/ module of the library, so a tool that links rzk cannot
-- import it. This module exposes it as part of the public API instead, together
-- with the rest of the build details, so a consumer (the @rzk@ executable, the
-- rzk-game) can report which checker it is running.
module Rzk.Version (
  -- * The package version
  version,
  versionString,

  -- * The full build description
  VersionInfo (..),
  LspSupport (..),
  versionInfo,
  ppVersionInfo,
) where

import           Data.Aeson                 (ToJSON (..), object, (.=))
import           Data.Version               (Version, showVersion)
import           Language.Haskell.TH.Syntax (lift, runIO)
import           System.Environment         (lookupEnv)
import qualified System.Info

import qualified Paths_rzk

-- | The version of the @rzk@ package.
version :: Version
version = Paths_rzk.version

-- | The version of the @rzk@ package, rendered as a string (e.g. @"0.11.2"@).
--
-- This is what @rzk version@ prints, and tools scrape it as such, so it is
-- deliberately just the version and nothing else.
versionString :: String
versionString = showVersion version

-- | Whether this build can act as an LSP server (@rzk lsp@).
--
-- LSP support is behind the @lsp@ Cabal flag, which is on by default for GHC
-- and unavailable for the JavaScript and WebAssembly backends. A tool that
-- wants to start a language server can consult this instead of running
-- @rzk lsp@ and seeing whether it fails.
data LspSupport
  = LspSupported
  | LspUnsupported
  deriving (Eq, Show)

-- | Everything this build knows about itself.
data VersionInfo = VersionInfo
  { versionInfoVersion   :: Version
    -- ^ The package version.
  , versionInfoCommit    :: Maybe String
    -- ^ The commit rzk was built from, when the build supplied one (see
    -- 'versionInfo'); 'Nothing' otherwise.
  , versionInfoCompiler  :: String
    -- ^ The Haskell implementation, e.g. @"ghc-9.10.3"@.
  , versionInfoPlatform  :: String
    -- ^ Operating system and architecture, e.g. @"darwin-aarch64"@.
  , versionInfoLsp       :: LspSupport
    -- ^ Whether @rzk lsp@ works in this build.
  } deriving (Eq, Show)

-- | The build description of the running rzk.
--
-- The commit is baked in from the @RZK_GIT_COMMIT@ environment variable as it
-- stood when this module was compiled; the release workflow sets it, and an
-- ordinary build leaves it unset and reports 'Nothing'. To stamp a local build:
--
-- > RZK_GIT_COMMIT=$(git rev-parse --short HEAD) \
-- >   stack build --force-dirty --ghc-options=-fforce-recomp
--
-- Neither stack nor GHC tracks the environment for recompilation, hence the
-- forcing: a build that changes nothing but @RZK_GIT_COMMIT@ keeps the commit
-- the module was last compiled with. CI builds from a clean tree, so a release
-- binary always carries the commit it was made from.
versionInfo :: VersionInfo
versionInfo = VersionInfo
  { versionInfoVersion  = version
  , versionInfoCommit   = $(runIO (lookupEnv "RZK_GIT_COMMIT") >>= lift)
  , versionInfoCompiler =
      System.Info.compilerName <> "-" <> showVersion System.Info.fullCompilerVersion
  , versionInfoPlatform = System.Info.os <> "-" <> System.Info.arch
  , versionInfoLsp      =
#ifdef LSP_ENABLED
      LspSupported
#else
      LspUnsupported
#endif
  }

-- | Render a build description as a block of lines, as printed by
-- @rzk version --full@.
ppVersionInfo :: VersionInfo -> String
ppVersionInfo VersionInfo{..} = unlines
  [ "rzk " <> showVersion versionInfoVersion <> commitSuffix
  , "built with: " <> versionInfoCompiler
  , "platform:   " <> versionInfoPlatform
  , "LSP:        " <> lspSupport
  ]
  where
    commitSuffix = case versionInfoCommit of
      Nothing     -> " (commit unknown)"
      Just commit -> " (" <> commit <> ")"
    lspSupport = case versionInfoLsp of
      LspSupported   -> "supported"
      LspUnsupported -> "not supported in this build"

instance ToJSON LspSupport where
  toJSON LspSupported   = toJSON True
  toJSON LspUnsupported = toJSON False

instance ToJSON VersionInfo where
  toJSON VersionInfo{..} = object
    [ "version"  .= showVersion versionInfoVersion
    , "commit"   .= versionInfoCommit
    , "compiler" .= versionInfoCompiler
    , "platform" .= versionInfoPlatform
    , "lsp"      .= versionInfoLsp
    ]
