-- | The version of the @rzk@ package, re-exported from the Cabal-generated
-- @Paths_rzk@ module.
--
-- @Paths_rzk@ is an autogenerated /other/ module of the library, so it is not
-- importable by consumers. This module gives them the version instead, which is
-- useful for tools that link the library and want to report which rzk they are
-- built against (the @rzk@ executable itself uses it for @rzk version@).
module Rzk.Version (
  version,
  versionString,
) where

import           Data.Version (Version, showVersion)

import qualified Paths_rzk

-- | The version of the @rzk@ package.
version :: Version
version = Paths_rzk.version

-- | The version of the @rzk@ package, rendered as a string (e.g. @"0.11.2"@).
versionString :: String
versionString = showVersion version
